### ISSUE TITLE
Removal of biogo dependency and some extention of faidx

### ISSUE THREAD

**Issue by shenwei356** [brentp/faidx#1]
Hi @brentp ,

Thanks for this package, I was intend to use it in [`fakit`](https://github.com/shenwei356/fakit), but I found the FASTA index parser depends on `biogo`. It may be a little heavy weight just for this function. And `biogo` seems do not support creating .fai (of cause, `samtools` does).

I was intend to fork and edit your code, but then I found that there will be much more alters. So I implemented it in my [`bio/seqio/fai`](https://github.com/shenwei356/bio/tree/master/seqio/fai) repo. 

Code of fai data structure were copied and edited from `biogo`,  But I wrote the code of creating and reading fai, and so did test code. Code of random accessing subsequences were copied from you, but I extended them a lot. I think there's no problem about of LICENCE, is it?

Hope it be helpful.

Sincerely,
Wei

**Comment by brentp** [comment]
sure. no problem. Also check out the latest commit where I stats `Stats()` method. Might be useful to expose in your fakit.

**Comment by shenwei356** [comment]
I saw your update. But I thinks it's not necessary, cause one can `Get` the subsequence and compute GC content by themselves or by other functions provided by other packages. 

For the `mmap`, it's not memory-efficient for large file, e.g., human genome. Seek is fast enough most of time.  So I make it [optional](https://github.com/shenwei356/bio/blob/master/seqio/fai/faidx.go#L11).

fakit has been renamed to [SeqKit](https://github.com/shenwei356/seqkit), and it's accepted by PLOS ONE today.

**Comment by brentp** [comment]
congrats on the paper.

**Comment by shenwei356** [comment]
Thanks for your valuable comments on the first manuscript.
